#  Port this server is being ran on
port: 8091
#  URL for anchor platform server
anchorPlatformUrl: "http://localhost:8085"
# When true, enables test endpoints
enableTest: true
# Indicates, that custody integration is enabled
custodyEnabled: false
# Indicates, that RPC requests should be used instead of PATCH /transactions endpoint
rpcEnabled: true
sep24:
  #  URL for horizon server
  horizonUrl: "https://horizon-testnet.stellar.org"
  # Secret key used to send funds to user accounts.
  # Public key: GABCKCYPAGDDQMSCTMSBO7C2L34NU3XXCW7LR4VVSWCCXMAJY3B4YCZP
  secret: "SAJW2O2NH5QMMVWYAN352OEXS2RUY675A2HPK5HEG2FRR2NXPYA4OLYN"
  # Encryption key for interactive JWT
  interactiveJwtKey: "secret_sep24_interactive_url_jwt_secret"
sep31:
  # The Stellar wallet to which the customer will send the Stellar assets.
  distributionWallet: GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF
  distributionWalletMemo:
  distributionWalletMemoType:
